# Copyright (C) 2024 OpenDLV

image: docker

variables:
  PLATFORMS: "linux/amd64,linux/arm64,linux/arm/v7"

services:
  - name: docker:dind

stages:
  - build
  - deploy

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build-amd64:
  tags:
    - docker-build
  stage: build
  script:
    - docker build .
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

release:
  tags:
    - docker-build
  stage: deploy
  image: docker:24.0.5  # Explicitly use a version that works well
  services:
    - name: docker:dind
      command: ["--experimental", "--storage-driver=overlay2"]
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - apk add --no-cache curl jq
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker run --privileged --rm tonistiigi/binfmt --install all
    - docker buildx create --use --name mybuilder --driver docker-container
    - docker buildx inspect --bootstrap
    - docker buildx build --platform "$PLATFORMS" -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG" --push .
  rules:
    - if: $CI_COMMIT_TAG =~ /^[0-9.]+$/
